<?php

/**
 * @file
 * VLSuite - Block - Image main module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\vlsuite_block_image\Entity\Bundle\VLSuiteBlockImage;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function vlsuite_block_image_entity_bundle_info_alter(array &$bundles): void {
  if (!empty($bundles['block_content'][VLSuiteBlockImage::BUNDLE_KEY])) {
    $bundles['block_content'][VLSuiteBlockImage::BUNDLE_KEY]['class'] = VLSuiteBlockImage::class;
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function vlsuite_block_image_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Use link field to link image (responsive image allows to set url).
  if ($entity->getEntityTypeId() === 'block_content' && $entity->bundle() === VLSuiteBlockImage::BUNDLE_KEY &&
    !empty($build['vlsuite_image']) && !empty($build['vlsuite_link'])) {
    foreach (Element::children($build['vlsuite_image']) as $delta) {
      $build['vlsuite_image'][$delta]['#url'] = $build['vlsuite_link'][$delta]['#url'] ?? NULL;
    }
    $build['vlsuite_link']['#access'] = FALSE;
  }
}
