<?php

/**
 * @file
 * VLSuite - Collection - Card main module file.
 */

use Drupal\vlsuite_collection_card\Entity\Bundle\VLSuiteCollectionCard;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function vlsuite_collection_card_entity_bundle_info_alter(array &$bundles): void {
  if (!empty($bundles['block_content'][VLSuiteCollectionCard::BUNDLE_KEY])) {
    $bundles['block_content'][VLSuiteCollectionCard::BUNDLE_KEY]['class'] = VLSuiteCollectionCard::class;
  }
}
