<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Hello world module file.
 *
 * Implements hook_help().
 */
function hello_world_luna_help($route_name, RouteMatchInterface $route_match){
    switch($route_name) {
        case 'help.page.hello_world':
            $output = '';
            $output .= '<h3>'.t('About').'</h3>';
            $output .= '<p>'.t('This is a example module').'</p>';

            return $output;
    }
}
