<?php

/**
 * @file
 * VLSuite - Collection - Gallery main module file.
 */

use Drupal\vlsuite_collection_gallery\Entity\Bundle\VLSuiteCollectionGallery;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function vlsuite_collection_gallery_entity_bundle_info_alter(array &$bundles): void {
  if (!empty($bundles['block_content'][VLSuiteCollectionGallery::BUNDLE_KEY])) {
    $bundles['block_content'][VLSuiteCollectionGallery::BUNDLE_KEY]['class'] = VLSuiteCollectionGallery::class;
  }
}

/**
 * Implements hook_preprocess_block().
 */
function vlsuite_collection_gallery_preprocess_block(&$variables) {
  if ($variables['plugin_id'] === 'vlsuite_block_inline_block:vlsuite_collection_gallery') {
    $variables['#attached']['library'][] = 'vlsuite_collection_gallery/gallery';
  }
}
