<?php

/**
 * @file
 * VLSuite - Block - Local video main module file.
 */

use Drupal\vlsuite_block_local_video\Entity\Bundle\VLSuiteBlockLocalVideo;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function vlsuite_block_local_video_entity_bundle_info_alter(array &$bundles): void {
  if (!empty($bundles['block_content'][VLSuiteBlockLocalVideo::BUNDLE_KEY])) {
    $bundles['block_content'][VLSuiteBlockLocalVideo::BUNDLE_KEY]['class'] = VLSuiteBlockLocalVideo::class;
  }
}
