_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: acd618ab-5032-4e86-896e-45b3971fe64a
name: 'Prueba Técnica'
mail: info@ddev.com
slogan: ''
page:
  403: ''
  404: ''
  front: /search/user
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
