<?php

/**
 * @file
 * VLSuite - Block - Paragraph main module file.
 */

use Drupal\vlsuite_block_paragraph\Entity\Bundle\VLSuiteBlockParagraph;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function vlsuite_block_paragraph_entity_bundle_info_alter(array &$bundles): void {
  if (!empty($bundles['block_content'][VLSuiteBlockParagraph::BUNDLE_KEY])) {
    $bundles['block_content'][VLSuiteBlockParagraph::BUNDLE_KEY]['class'] = VLSuiteBlockParagraph::class;
  }
}
