<?php

/**
 * @file
 * VLSuite - Block - CTA main module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\vlsuite_block_cta\Entity\Bundle\VLSuiteBlockCta;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function vlsuite_block_cta_entity_bundle_info_alter(array &$bundles): void {
  if (!empty($bundles['block_content'][VLSuiteBlockCta::BUNDLE_KEY])) {
    $bundles['block_content'][VLSuiteBlockCta::BUNDLE_KEY]['class'] = VLSuiteBlockCta::class;
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function vlsuite_block_cta_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Block cta font icon inside link.
  if ($entity->getEntityTypeId() === 'block_content' && $entity->bundle() === VLSuiteBlockCta::BUNDLE_KEY &&
    !empty($build['vlsuite_link']) && !empty($build['vlsuite_icon_font_icon'])) {
    foreach (Element::children($build['vlsuite_link']) as $delta) {
      $title = $build['vlsuite_link'][$delta]['#title'];
      $build['vlsuite_link'][$delta]['#title'] = !empty($build['vlsuite_icon_font_icon'][$delta]) ? $build['vlsuite_icon_font_icon'][$delta] + ['#suffix' => $title] : $title;
    }
    $build['vlsuite_icon_font_icon']['#access'] = FALSE;
  }
}
