<?php

/**
 * @file
 * VLSuite - Collection - Hero install module file.
 */

use Drupal\vlsuite_collection_hero\Entity\Bundle\VLSuiteCollectionHero;

/**
 * Implements hook_install().
 */
function vlsuite_collection_hero_install() {
  \Drupal::service('vlsuite_bundle_field.helper')->installBlockContentBundleFields(VLSuiteCollectionHero::BUNDLE_KEY, VLSuiteCollectionHero::class);
  \Drupal::service('vlsuite_collection.helper')->generateMedia('vlsuite_image', '19b2383d-7801-4e8a-a9ee-092afec708c4', 'vlsuite_collection_hero', 'vlsuite-collection-placeholder-image.jpg', 'a1556bd3-5bd8-4fdc-a073-5c201984ad91');
  \Drupal::service('vlsuite_collection.helper')->sectionLibraryTemplateCreateFromYmlFile('d2ad3bd9-6acc-4860-83ec-54c6d57845eb', 'vlsuite_collection_hero', [
    'vlsuite_media' => '19b2383d-7801-4e8a-a9ee-092afec708c4',
    'vlsuite_background' => '19b2383d-7801-4e8a-a9ee-092afec708c4',
  ]);
}
